### ISSUE TITLE
Support custom instance socket path

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/ansible-cartridge#102]
## Summary

Add the ability to specify a custom path to the socket for every host.

## Motivation

The directory `/var/run/tarantool/` can not always be reached. This makes it impossible to use a role in such cases.

## Design Detail

Add optional string parameter `control_sock_path` to instance hostvars and change the function to get the socket.

```python
def get_instance_control_sock(instance_vars, stateboard=False):
    if instance_vars.get('control_sock_path'):
        return instance_vars['control_sock_path']

    return '/var/run/tarantool/{}.control'.format(
        get_instance_fullname(
            instance_vars['cartridge_app_name'],
            instance_vars['inventory_hostname'],
            stateboard))
```

Filter call will look like this:
```yaml
join_instance_sock: '{{ hostvars[join_host] | get_instance_control_sock }}'
```
## Drawbacks

When the ansible-cartridge role starts the instance, the default path `/var/run/tarantool` will be passed to it through from systemd unit. That is, specifying a custom path will not create a file socket, it must already exist.
Therefore, this feature is only suitable for managing an already created instances.

**Comment by dokshina** [comment]
Since #199 it's possible to pass `cartridge_run_dir` variable.
