### ISSUE TITLE
[2pt] Disable restart instance for hot reload

### ISSUE THREAD

**Issue by FizikRoot** [tarantool/ansible-cartridge#114]
I would like to be able to deliver a new version of the application without restarting the application.
Otherwise, the hot boot functionality does not make sense.
Something like
```
    cartridge_app_name: getting-started-app
    cartridge_package_path: ./getting-started-app-2.0.0-0.rpm 
    cartridge_restart_instance: false
    cartridge_enable_tarantool_repo: false
```

**Comment by dokshina** [comment]
We already have `restarted` flag to force instance restarting. I suggest using this flag to disable restarting:

* `restarted` is `true`: instance is restarted anyway;
* `restarted` is `false`: instance isn't restarted anyway;
* `restarted` isn't specified: role decides should instance be restarted or not.
