### ISSUE TITLE
Deploy TGZ: divide task into root and non-root 

### ISSUE THREAD

**Issue by savinov** [tarantool/ansible-cartridge#134]
https://github.com/tarantool/ansible-cartridge/tree/deploy-tgz-under-systemd
I have a suggestion about install_targz.yml: divide it into root and non-root tasks.
OS user creation, systemd unit configuration etc. are one-shot operations.
Tarball distribution rollout is a continuous operation.
It's a common case: one department of corporation configure OS (with root privileges) and another department configure CI to rollout tarball (without root privileges).

**Comment by no1seman** [comment]
When we use sudo systemctl * app@instance instead of ansible.builtin.systemd we have to add a task that checks the result of operation.
