### ISSUE TITLE
readme: broken links to cartridge configuration

### ISSUE THREAD

**Issue by RunsFor** [tarantool/ansible-cartridge#140]
https://github.com/tarantool/ansible-cartridge#instances

> Instance can be configured using the config variable. This variable describes instance parameters that would be passed to cartridge configuration. It can contain cluster-specific parameters or some application-specific parameters (can be parsed in application using the cartridge.argparse module).

**Comment by akudiyar** [comment]
More broken links were found: the ones heading for cartridge.argparse
https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.argparse/#cluster-opts
