### ISSUE TITLE
[2pt] Wait until instance becomes 'healthy' when bootstrapping big cluster

### ISSUE THREAD

**Issue by sharonovd** [tarantool/ansible-cartridge#145]
If an new replicaset does not become 'healthy' during mass join, ansible won't wait for him, and will stop pipeline

**Comment by opomuc** [comment]
I have an improved instance ready check: https://github.com/opomuc/ansible-cartridge/blob/master/library/cartridge_check_instance_started.py#L25

it also waits for RolesConfigured state in Cartridge. But it is not checking WHOLE cluster state.

Possible solution -- wait for RolesConfigured after each `edit_topology` call

**Comment by no1seman** [comment]
Generally we have to have the following checkers which will be helpful on different steps of playbooks:

is_healty - checks healthy of instance after some restart for example. Must check not only health status of the instance (alive, RolesConfigured) but also vshard bucket discovery process finished to indicate that storage exactly ready to go.
is_healty_stateboard - checks if stateboard is healthy and fully functional.
is_healhty_cluster - checks healthiness of whole cluster
is_healthy_replicaset - checks healthiness of whole replicaset. Will be useful to check replicaset health after edit topology and after changing weight of replicaset.

**Comment by dokshina** [comment]
I think that since this issue is named `Wait until INSTANCE becomes 'healthy'`  we can improve current is_healty check for instance (see #128)  and add add is_healty_stateboard check.

Other `healthy` problems will be solved within #142,
