### ISSUE TITLE
☂️[EPIC] 9k-noddes cluster 

### ISSUE THREAD

**Issue by sharonovd** [tarantool/ansible-cartridge#151]

**Comment by hackallcode** [comment]
Now we can deploy 500 Cartridge instances in 10 minutes, 1k TDG instances in 40 minutes without errors. The only thing is that we are using an inventory generator for this, but it is still in development. This issue can be closed, as there is a separate issue for the generator: https://github.com/tarantool/ansible-cartridge/issues/231
