### ISSUE TITLE
Failed to edit topology: Timeout exceeded

### ISSUE THREAD

**Issue by hackallcode** [tarantool/ansible-cartridge#169]
I have a cluster of 100 instances (10 replicas with 10 instances). When deploying Cartridge role, I very often (4 times out of 5) get the next error in the "Edit Topology" step after 10-15 seconds of executing:
`fatal: [tnt_50_external_1_core_1_1 -> 10.0.0.102]: FAILED! => {"changed": false, "msg": "Failed to edit topology: Timeout exceeded"}`.

Let's make it possible to configure the maximum timeout.

**Comment by dokshina** [comment]
See also https://github.com/tarantool/cartridge/issues/1145, https://github.com/tarantool/cartridge/issues/1142

**Comment by hackallcode** [comment]
As a temporary solution (without cartridge update), you can increase the timeout like this in `cartridge.post-build`:
```bash
awk '{gsub(/timeout = 5/, "timeout = 120")}1' .rocks/share/tarantool/cartridge/twophase.lua >temp.lua
mv temp.lua .rocks/share/tarantool/cartridge/twophase.lua
```

**Comment by rosik** [comment]
> As a temporary solution (without cartridge update), you can increase the timeout like this in `cartridge.post-build`:
> 
> ```shell
> awk '{gsub(/timeout = 5/, "timeout = 120")}1' .rocks/share/tarantool/cartridge/twophase.lua >temp.lua
> mv temp.lua .rocks/share/tarantool/cartridge/twophase.lua
> ```

Please, notice the fresh change: https://github.com/tarantool/cartridge/pull/1266/files#diff-63dd6d90ddea044f72afc2ab4c212b87eff00e05cb4602bf3c188f94240774bdR41-R42

```lua
-- cartridge/twophase.lua
vars:new('options', {
    netbox_call_timeout = 1,
    upload_config_timeout = 30,
    apply_config_timeout = 10,
})
```
