### ISSUE TITLE
Select control instance that exists in inventory file

### ISSUE THREAD

**Issue by hackallcode** [tarantool/ansible-cartridge#228]
I have an instance that is not in the inventory, but which is on a neighboring server on the same port. As a result, the instances find each other and `set_control_instance` tries to use an instance that is not in inventory. As a result, I get the error `FAILED! => {"changed": true, "msg": "u'INSTANCE_NAME '"}`.

Let's select control instance that exists in inventory (or play hosts).

**Comment by dokshina** [comment]
Closed via #239
