### ISSUE TITLE
[16pt] There is no fast way to create an inventory file for a cluster

### ISSUE THREAD

**Issue by opomuc** [tarantool/ansible-cartridge#231]
Suppose I have a cluster with 500 instances and 24 nodes. This is over 2k lines of inventory. I can't possibly do it manually.

In our project we have a custom `hosts.yml` generator that kinda solves our problem. One can change a number of variables (`storage_on_server`, `replicasets_in_cluster`, etc.) and will get a generated inventory for a project. I've seen 3 or 4 different variations of a such "generator". 

I want a tool, that can generate me a `hosts.yml` file from cluster description. What types of instances do I have? How many instances of type 1 I want? etc.

Something similar to helm charts:
https://github.com/tarantool/tarantool-operator/blob/master/examples/kv/helm-chart/values.yaml#L22
or Kubernetes manifest. This is just an example.

**Comment by hackallcode** [comment]
We made [ansible-cartridge-generator](https://github.com/tarantool/ansible-cartridge-generator) to solve this problem
