### ISSUE TITLE
Where should hosts.yml be placed?

### ISSUE THREAD

**Issue by qgx** [tarantool/ansible-cartridge#25]
Where should hosts.yml be placed, or how do I call this file?
$ tree
.
├── hosts.yml
├── playbook.yml
└── roles
    └── ansible-cartridge
         ├── CHANGELOG.md
        ├── create-packages.sh
...

$ cat playbook.yml
---
- name: Deploy my Tarantool Cartridge app
  hosts: all
  become: true
  become_user: root
  vars_files:
    - hosts.yml
  tasks:
  - name: Import Tarantool Cartridge role
    import_role:
      name: ansible-cartridge

$ ansible-playbook playbook.yml

PLAY [Deploy my Tarantool Cartridge app] *****************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************
ok: [host1]

TASK [ansible-cartridge : Fail for other distributions] **************************************************************************************************
skipping: [host1]

TASK [ansible-cartridge : Set cartridge_confdir and package_updated variables] ***************************************************************************
ok: [host1]

TASK [ansible-cartridge : Set remote_user for delegated tasks] *******************************************************************************************
ok: [host1]

TASK [ansible-cartridge : Validate config] ***************************************************************************************************************
fatal: [host1 -> localhost]: FAILED! => {"changed": false, "msg": "At least one of `cartridge_app_name` and `cartridge_package_path` must be specified

**Comment by dokshina** [comment]
Did you specify `cartridge_package_path` or `cartridge_app_name ` variable?

**Comment by qgx** [comment]
I put the hosts.yml in the readme into the Inventory. Need to split hosts.yml into group_vars and host_vars, it works, thank you
