### ISSUE TITLE
doc: broken getting started guide link in readme

### ISSUE THREAD

**Issue by RunsFor** [tarantool/ansible-cartridge#255]
> See the getting started guide to learn how to set up topology using this role.

**Comment by dokshina** [comment]
There is no getting started guide (yet) and I didn't see this line in readme.

**Comment by RunsFor** [comment]
Fixed in https://github.com/tarantool/ansible-cartridge/commit/c8fca5b12c792d91eed3e5bd979d4e3d59426e7a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L11. Closing
