### ISSUE TITLE
[2pt] edit_topology fails if at least one replicaset alias in runnig cluster is not equal to those replicaset alias in ansible inventory

### ISSUE THREAD

**Issue by no1seman** [tarantool/ansible-cartridge#362]
Steps to reproduce:

1. Rollout cluster with some inventory
2. Change replicaset alias in Cartridge UI
3. Run any playbook with edit_topology step

After that you will face the following error: 
Failed to edit topology: servers[xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx].uri "advertise_uri:port" collision with another server

**Comment by hackallcode** [comment]
We identify replicasets by aliases, since we don't know their UUIDs.
Therefore, it is necessary to add UUID to inventory (what a bad way). If there was a renaming via UI, then you should also do it in inventory.
