### ISSUE TITLE
[3sp] Add `cartridge_log_dir` to the update_package step

### ISSUE THREAD

**Issue by opomuc** [tarantool/ansible-cartridge#378]
`update_package` has the creation of `wal`, `run`, `conf`, `data`, `memtx` and even `vinyl` directories. But no logs... Sometimes we want to place logs onto a different mount, so It won't trash our `wal` dir. In that case we need to have a directory present.

For example, `cartridge_log_dir: /data/tarantool/logs/<app_name>/`

If I understand correctly all those directories are created on a condition if the variable is defined? Can we add logs then?

**Comment by hackallcode** [comment]
What way do you use to specify the logs directory?

**Comment by opomuc** [comment]
Through `box.cfg` option `log`. Tarantool does not create directories by itself, so if you specify a missing directory in `log` parameter -- Tarantool fails to start.
