### ISSUE TITLE
[4sp] Make possible to run Cache facts and Collect instance info only once for multitask playbooks

### ISSUE THREAD

**Issue by no1seman** [tarantool/ansible-cartridge#379]

**Comment by hackallcode** [comment]
In artificial conditions, `Collect instance info` now takes no more than 30 seconds for 1024 instances, and at any import (first, second...). Of these, it takes 20 seconds for Ansible to launch the task. Caching this step is dangerous, as it checks the current state of the cluster to determine the operating logic.

@no1seman @opomuc, please check how long the `Collect instance info` task now takes to understand the need for caching.

**Comment by artur-barsegyan** [comment]
@no1seman @opomuc Any feedback?

**Comment by no1seman** [comment]
Optimisation is quite good, but the core problem that Collect instance fired on every serie is not solved.

**Comment by opomuc** [comment]
Gently closing since repo is deprecated.
