### ISSUE TITLE
Используется только N символов куки

### ISSUE THREAD

**Issue by Thorwinz** [tarantool/ansible-cartridge#390]
Tarantool 2.7.3-0-gdddf926
Target: Linux-x86_64-RelWithDebInfo

Разворачиваем два независимых кластера приложения. Разворачиваем через ansible, у каждого из кластеров свой cartridge_cluster_cookie.

**Проблема:**
При развертывании второго кластера находится первый (несмотря на то, что кластер-куки отличается!), и в итоге не может второй кластер забутстрапиться.

fatal: [node_1d -> tarXX-router]: FAILED! => {"changed": false, "msg": "Membership contains instance node_1b that isn't described in inventory"}

**Выявлено:**

Для пары: 
msx-secret-cookie
msy-secret-cookie 
Оба кластера **успешно** разворачиваются

Для такой пары:
message-storage-x-secret-cookie
message-storage-y-secret-cookie
Происходит **FAILED**

**Comment by hackallcode** [comment]
It looks like this problem is in Cartridge's code. Ansible only uses a cookie to put it in a file on disk. This error indicates that the instances of the specified two clusters have found each other, most likely on their own

**Comment by filonenko-mikhail** [comment]
Check both clusters cooki:

```
cl = require('cartridge.cluster-cookie')
cl.cookie()
```

**Comment by Thorwinz** [comment]
На кластере, где кука длинная:
```
$ tarantoolctl connect admin:message-storage-x-secret-cookie@tarantool-2-6:3351
connected to tarantool-2-6:3351
tarantool-2-6:3351> cl = require('cartridge.cluster-cookie')
---
...

tarantool-2-6:3351> cl.cookie()
---
- message-storage-x-secret-cookie
...

tarantool-2-6:3351>
$ tarantoolctl connect admin:message-storage-y-secret-cookie@tarXX-router:3353
connected to tarXX-router:3353
tarXX-router:3353> cl = require('cartridge.cluster-cookie')
---
...

tarXX-router:3353> cl.cookie()
---
- message-storage-y-secret-cookie
...
```

**Comment by artur-barsegyan** [comment]
@Thorwinz кажется, это баг каржа. Перенесешь тикет?

**Comment by Thorwinz** [comment]
> @Torwinz кажется, это баг каржа. Перенесешь билет?

Ок, но сначала Мишей согласую

**Comment by Thorwinz** [comment]
> > @Torwinz кажется, это баг каржа. Перенесешь билет?
> 
> Ок, но сначала Мишей согласую

Согласовал/перезавел https://github.com/tarantool/cartridge/issues/1768

**Comment by Thorwinz** [comment]
Согласовал/перезавел https://github.com/tarantool/cartridge/issues/1768
