### ISSUE TITLE
Актуализовать список динамических box.cfg параметров

### ISSUE THREAD

**Issue by opomuc** [tarantool/ansible-cartridge#395]
Есть два списка:
`dynamic_skip_at_load`: https://github.com/tarantool/tarantool/blob/master/src/box/lua/load_cfg.lua#L405
`dynamic_cfg`: https://github.com/tarantool/tarantool/blob/master/src/box/lua/load_cfg.lua#L288

Ни один из скисков не совпадает со [внутренним списком ansible-cartridge](https://github.com/tarantool/ansible-cartridge/blob/master/module_utils/helpers.py#L15).

как минимум параметр `memtx_max_tuple_size` не изменяется с помощью `runtime_settings` плейбуков

**Comment by hackallcode** [comment]
`dynamic_cfg_skip_at_load` obviously does not contain all the parameters that can be changed at runtime.

`dynamic_cfg` has options that are described in the documentation as NOT dynamic. Also, it does not have a dynamic (according to the documentation) `panic_on_wal_error` parameter (maybe it's a bug).

According to the documentation, we are missing only the following parameters: `election_timeout`, `election_mode`, `replication`, `memtx_max_tuple_size`, `panic_on_wal_error`.

Do you know which list to base on?
