### ISSUE TITLE
[4pt] Add step to backup not started instance

### ISSUE THREAD

**Issue by hackallcode** [tarantool/ansible-cartridge#405]
The current backup step can only back up running instances. In some cases this is useless.

**Comment by artur-barsegyan** [comment]
@sharonovd Who uses backup via Ansible in Delivery?

**Comment by sharonovd** [comment]
@opomuc ?

**Comment by hackallcode** [comment]
@artur-barsegyan , for example, this is useful for moving instances from one host to another. It can be used by anyone from Delivery or Presale

**Comment by opomuc** [comment]
what @hackallcode means, is that in order to move instances between servers you have to stop them first. But `ansible-cartridge` playbooks are not backing up stopped instances

**Comment by artur-barsegyan** [comment]
> what @hackallcode means, is that in order to move instances between servers you have to stop them first. But `ansible-cartridge` playbooks are not backing up stopped instances

Thank you for details. That ticket is the part of scaling procedure. 

Personally discussed with @hackallcode that he can do it and it won't take long.
