### ISSUE TITLE
[5pt] backup: do not start snapshoting if snapshot is in progress

### ISSUE THREAD

**Issue by opomuc** [tarantool/ansible-cartridge#416]
Tarantool has `box.info.gc().checkpoint_is_in_progress`

**Comment by artur-barsegyan** [comment]
А как это стреляет или вообще как мешает?

**Comment by opomuc** [comment]
Это ломает процесс бэкапа. Стреляет почти всегда на больших кластерах. Чем больше инстансов, тем больше вероятность

**Comment by kdy999** [comment]
Подтверждаю, при этом после ошибки инстансы остаются со статусом backup.start

**Comment by olegrok** [comment]
Со стороны Scaling/TDG проблем нет. Надо вернуть в Hteam.

@tupikinm, забери, пожалуйста

**Comment by opomuc** [comment]
Sorry, but repository is deprecated and this won't be fixed.
