### ISSUE TITLE
Can not past the getting started guide

### ISSUE THREAD

**Issue by palage4a** [tarantool/ansible-cartridge#424]
I am getting the error:
<img width="1887" alt="image" src="https://github.com/tarantool/ansible-cartridge/assets/42588176/a54b9da3-09bb-4652-a47c-264fe27ef039">

I suppose that the problem is the `cartrdige_custom_steps_dir` variable is `None` by default,
https://github.com/tarantool/ansible-cartridge/blob/bb85d618891461b7619567dbf088d10d939f629e/defaults/main.yml#L15-L17
but it is required and must has the `string` type:
https://github.com/tarantool/ansible-cartridge/blob/bb85d618891461b7619567dbf088d10d939f629e/library/cartridge_get_scenario_steps.py#L7-L15

**Comment by p7nov** [comment]
Same for scenario: the [default](https://github.com/tarantool/ansible-cartridge/blob/master/doc/scenario.md#scenario-default) is defined but the `cartridge_scenario` is required.

```
TASK [tarantool.cartridge : Collect tasks for scenario steps] ***************************************************************************************************************************
fatal: [app-01 -> localhost]: FAILED! => {"changed": false, "msg": "argument 'scenario' is of type <class 'NoneType'> and we were unable to convert to list: <class 'NoneType'> cannot be converted to a list"}
```

Note that both these parameters weren't required before and everything worked as described in the guide.

**Comment by opomuc** [comment]
Please provide `cartridge_scenario` and `cartridge_custom_steps_dir` as they are indeed required.

Gently closing since repo is deprecated and this won't be fixed.
