### ISSUE TITLE
Can't set `validate_config_timeout`

### ISSUE THREAD

**Issue by palage4a** [tarantool/ansible-cartridge#425]
On highloaded clusters we have problems with updating the clusterwide config with default values of timeouts.
We can increase some of them, for example: 
https://github.com/tarantool/ansible-cartridge/blob/bb85d618891461b7619567dbf088d10d939f629e/doc/variables.md?plain=1#L134-L139

But we can't set `validate_config_timeout`, which is bottleneck, since this timeout affects the "prepare" phase of applying CW-config.  This phase has a lot of implicit yields, since there are a lot of IO operations.

**Comment by opomuc** [comment]
Gently closing since repo is deprecated and this won't be fixed.
