### ISSUE TITLE
Which license is supposed to be used for that role?

### ISSUE THREAD

**Issue by tgadiev** [tarantool/ansible-cartridge#54]
The license type is unclear from published documentation.

**Comment by knazarov** [comment]
@tgadiev what do you mean? The code of the ansible role is licensed under the MIT license (as usual for other tarantool open source projects)

**Comment by tgadiev** [comment]
Ok. But it's not mentioned anywhere.

**Comment by tgadiev** [comment]
I see another misconception. You state that code is licensed under the MIT license but meta file states that
```yaml
license: 'BSD' 
```

**Comment by dokshina** [comment]
Yes, it’s my fault. Thanks for your comment, I will fix it ASAP.

**Comment by dokshina** [comment]
Added LICESNE and updated meta file.
