### ISSUE TITLE
Please add feature to support vshard group

### ISSUE THREAD

**Issue by Fedora7** [tarantool/ansible-cartridge#57]
Please add feature to support vshard group. By default, it can assume the default group is used when there is no other vshard group is configed. Thanks.

**Comment by dokshina** [comment]
@artur-barsegyan @knazarov what do you think about this feature?

**Comment by artur-barsegyan** [comment]
I think that is an essential feature. 

@Fedora7 I'm curious: what kind of task you want to resolve with some vshard groups?

**Comment by Fedora7** [comment]
@artur-barsegyan  I plan to use vhard groups for the following scenario:  one group for frequent updated, fast access data on small amount of high end and expensive servers, one group for massive  data only require medium or slow access on large amount of low end servers with more storage.  Since the hardware requirement and cost are different, we prefer to use different vshard bucket distribution for these different groups. The application code needs to access both  fast and slow data.

**Comment by artur-barsegyan** [comment]
@Fedora7 Thank you, for your detailed response. 
Still waiting @knazarov.

**Comment by knazarov** [comment]
I'm positive about this feature. Let's do it.
