### ISSUE TITLE
A string is more convenient as log level than a number

### ISSUE THREAD

**Issue by Kasen** [tarantool/ansible-cartridge#74]
I think 'error', 'warn', 'info' and others are more obvious for the user.

**Comment by dokshina** [comment]
Values from `config` section are passed directly to instance configuration file "as is". Then, cartridge uses  [`cartridge.argparse`](https://github.com/tarantool/cartridge/blob/master/cartridge/argparse.lua) module to get `box` options and pass them to `cartridge.cfg` call. 

But your application can use `cartridge.argparse` to get `warn`, `error` or `info` value, convert it to `box`-specific value and pass to `cartridge.cfg`.

**Comment by dokshina** [comment]
BTW, it seems to be possible since https://github.com/tarantool/tarantool/commit/a94a9b3fd629b5abbc99a23ba527cd91e5c6ebf5.
